const canvas=document.querySelector('#world');const ctx=canvas.getContext('2d');const audio=document.querySelector('#audio');
const songTitle=document.querySelector('#songTitle'),worldName=document.querySelector('#worldName'),waveEl=document.querySelector('#wave'),threatEl=document.querySelector('#threat'),intensityBar=document.querySelector('#intensityBar'),echoBar=document.querySelector('#echoBar');
let W=innerWidth,H=innerHeight,dpr=Math.min(devicePixelRatio||1,2);function resize(){W=innerWidth;H=innerHeight;canvas.width=W*dpr;canvas.height=H*dpr;ctx.setTransform(dpr,0,0,dpr,0,0)}addEventListener('resize',resize);resize();
const keys=new Set();addEventListener('keydown',e=>{keys.add(e.key.toLowerCase());if([' ','arrowup','arrowdown','arrowleft','arrowright'].includes(e.key.toLowerCase()))e.preventDefault()});addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));
const p={x:0,y:0,r:15,speed:2.5,stamina:1,dodge:0};let t=0,last=performance.now(),wave=1,waveTime=0,spawnTimer=0,monsters=[],portalTimer=5,portalFlash=0;
const worlds=[['CALM MEADOW','#152a2d','#72d6c8'],['NEON CITY','#17142d','#d08cff'],['PAPER FOREST','#332a25','#f4d4a2'],['CANDY PLAINS','#35213d','#ff8bd8'],['VOID GARDEN','#050509','#d9d9ff'],['GLITCH DESERT','#292414','#e7d46b']];let worldIndex=0;
let analyser=null,audioData=null,audioReady=false,lastBeat=0,beatPulse=0,audioLevel=0,bass=0,treble=0;
function setupAudio(){if(analyser)return;try{const ac=new (window.AudioContext||window.webkitAudioContext)();const source=ac.createMediaElementSource(audio);analyser=ac.createAnalyser();analyser.fftSize=256;analyser.smoothingTimeConstant=.78;source.connect(analyser);analyser.connect(ac.destination);audioData=new Uint8Array(analyser.frequencyBinCount);audioReady=true;audio.addEventListener('play',()=>ac.resume())}catch(e){console.warn('Audio analysis unavailable',e)}}
function analyzeAudio(){if(!analyser){audioLevel=.08+Math.sin(t*2)*.02;bass=audioLevel;treble=audioLevel;return}analyser.getByteFrequencyData(audioData);let total=0,low=0,high=0;for(let i=0;i<audioData.length;i++){const v=audioData[i]/255;total+=v;if(i<audioData.length*.18)low+=v;if(i>audioData.length*.55)high+=v}audioLevel=total/audioData.length;bass=low/(audioData.length*.18);treble=high/(audioData.length*.45);const beat=bass>.58&&audioLevel>.22;if(beat&&t-lastBeat>.16){beatPulse=1;lastBeat=t}beatPulse=Math.max(0,beatPulse-deltaTime*3.5)}
let deltaTime=.016;
function resetWorld(){p.x=0;p.y=0;monsters=[];wave=1;waveTime=0;portalTimer=4;worldIndex=Math.floor(Math.random()*worlds.length);worldName.textContent=worlds[worldIndex][0]}
function spawn(){const a=Math.random()*Math.PI*2;const d=Math.max(W,H)*(.45+Math.random()*.3);const type=bass>.68?1:treble>.6?2:Math.floor(Math.random()*3);monsters.push({x:p.x+Math.cos(a)*d,y:p.y+Math.sin(a)*d,r:10+Math.random()*10,phase:Math.random()*10,type,life:1})}
function update(dt){deltaTime=dt;t+=dt;waveTime+=dt;portalTimer-=dt;portalFlash=Math.max(0,portalFlash-dt);analyzeAudio();const danger=Math.min(1,Math.max(audioLevel*1.9,bass*1.25));if(portalTimer<=0&&danger>.25){portalTimer=Math.max(2,6-danger*3);portalFlash=.5;if(Math.random()<.65)spawn()}spawnTimer-=dt;if(spawnTimer<=0&&wave>1&&danger>.18){spawn();spawnTimer=Math.max(.22,1.4-wave*.28-danger*.55)}if(waveTime>12){waveTime=0;wave++;if(wave>3){resetWorld()}}let dx=0,dy=0;if(keys.has('w')||keys.has('arrowup'))dy--;if(keys.has('s')||keys.has('arrowdown'))dy++;if(keys.has('a')||keys.has('arrowleft'))dx--;if(keys.has('d')||keys.has('arrowright'))dx++;const len=Math.hypot(dx,dy)||1;let sp=p.speed*(keys.has('shift')?1.7:1);if(keys.has(' ')&&p.dodge<=0&&p.stamina>.2){p.dodge=.28;p.stamina-=.2}if(p.dodge>0){p.dodge-=dt;sp*=3.2}p.x+=dx/len*sp*60*dt;p.y+=dy/len*sp*60*dt;p.stamina=Math.min(1,p.stamina+dt*.12);for(const m of monsters){const a=Math.atan2(p.y-m.y,p.x-m.x);const speed=(m.type===1?1.8:1.25)*60*(.75+danger*.7);m.x+=Math.cos(a)*speed*dt;m.y+=Math.sin(a)*speed*dt;m.life-=dt*.015}monsters=monsters.filter(m=>Math.hypot(m.x-p.x,m.y-p.y)<Math.max(W,H)*.8&&m.life>0);const calm=wave===1&&danger<.2;const intensity=Math.min(1,danger*.72+wave*.08+beatPulse*.28);intensityBar.style.width=`${intensity*100}%`;echoBar.style.width=`${Math.min(100,20+monsters.length*9+bass*30+treble*15)}%`;waveEl.textContent=`${wave} / 3`;threatEl.textContent=calm?'CALM':intensity<.45?'TENSION':intensity<.7?'STORM':'CHAOS'}
function draw(){const [name,bg,accent]=worlds[worldIndex];const danger=Math.min(1,Math.max(audioLevel*1.9,bass*1.25));ctx.fillStyle=bg;ctx.fillRect(0,0,W,H);const storm=wave>1||danger>.28;const grid=70;ctx.save();ctx.translate(W/2-p.x,H/2-p.y);ctx.strokeStyle=accent+Math.floor((.08+danger*.12)*255).toString(16).padStart(2,'0');ctx.lineWidth=1;for(let x=-2000;x<2000;x+=grid){ctx.beginPath();ctx.moveTo(x,-2000);ctx.lineTo(x,2000);ctx.stroke()}for(let y=-2000;y<2000;y+=grid){ctx.beginPath();ctx.moveTo(-2000,y);ctx.lineTo(2000,y);ctx.stroke()}if(storm){for(let i=0;i<8;i++){const a=t*(.3+i*.04)+i;const x=Math.cos(a)*350,y=Math.sin(a*1.7)*220;ctx.strokeStyle=accent+Math.floor((.18+danger*.35)*255).toString(16).padStart(2,'0');ctx.beginPath();ctx.arc(x,y,30+Math.sin(t*4+i)*12+beatPulse*35,0,Math.PI*2);ctx.stroke()}}if(portalFlash>0){ctx.strokeStyle=accent;ctx.lineWidth=4;ctx.shadowBlur=30;ctx.shadowColor=accent;ctx.beginPath();ctx.arc(0,0,80+Math.sin(t*18)*15,0,Math.PI*2);ctx.stroke();ctx.shadowBlur=0}for(const m of monsters){ctx.save();ctx.translate(m.x,m.y);const pulse=1+Math.sin(t*7+m.phase)*.2+beatPulse*.18;ctx.scale(pulse,pulse);ctx.shadowBlur=18+danger*20;ctx.shadowColor=accent;ctx.fillStyle='#080811';ctx.beginPath();ctx.arc(0,0,m.r+(m.type===1?4:0),0,Math.PI*2);ctx.fill();ctx.strokeStyle=accent;ctx.lineWidth=2+danger*2;ctx.stroke();ctx.strokeStyle=accent+'aa';for(let i=0;i<3;i++){ctx.beginPath();ctx.arc(0,0,m.r+8+i*6,-.8+i*.3,.8+i*.3);ctx.stroke()}ctx.restore()}ctx.shadowBlur=20;ctx.shadowColor=accent;ctx.fillStyle='#f5f7ff';ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.strokeStyle=accent;ctx.lineWidth=3;ctx.stroke();ctx.restore();if(storm){ctx.fillStyle=accent+Math.floor((.03+danger*.07)*255).toString(16).padStart(2,'0');ctx.fillRect(0,0,W,H)}if(beatPulse>0){ctx.fillStyle='#ffffff'+Math.floor(beatPulse*35).toString(16).padStart(2,'0');ctx.fillRect(0,0,W,H)}}
function loop(now){const dt=Math.min((now-last)/1000,.033);last=now;update(dt);draw();requestAnimationFrame(loop)}requestAnimationFrame(loop);
document.querySelector('#audioInput').addEventListener('change',e=>{const f=e.target.files[0];if(!f)return;setupAudio();audio.src=URL.createObjectURL(f);songTitle.textContent=f.name.replace(/\.[^/.]+$/,'');audio.play().catch(()=>{});resetWorld()});