const keys=new Set();
const player={x:0,y:0,r:16,health:1,stamina:1,calm:1,vx:0,vy:0,invuln:0,dodge:0,attack:0};
let audioCtx=null,analyser=null,source=null,freq=null,last=performance.now(),spawnClock=0,mutationClock=0;
const vfxEvents=[];
const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v));
const monsterType=k=>k===1?'BASS':k===2?'TREBLE':k===3?'VOCAL':'RHYTHM';
const monsterEntry=e=>e===0?'GROUND':e===1?'SKY':'PORTAL';
function presentMonsters(frame){return (frame?.monsters||[]).map(m=>({...m,type:monsterType(m.kind),entry:monsterEntry(m.entry),state:(m.state===5||m.state===6||m.state===7)?'telegraph':'active',telegraph:m.state===5||m.state===6||m.state===7}));}
function pushVFX(type,x,y,intensity,extra={}){vfxEvents.push({type,x,y,intensity:clamp(intensity),life:0,maxLife:extra.maxLife??.7,...extra});if(vfxEvents.length>80)vfxEvents.splice(0,vfxEvents.length-80)}
function updateVFX(dt){for(let i=vfxEvents.length-1;i>=0;i--){vfxEvents[i].life+=dt;if(vfxEvents[i].life>=vfxEvents[i].maxLife)vfxEvents.splice(i,1)}}
function setupAudio(){const audio=document.querySelector('#audio');const input=document.querySelector('#audioInput');input?.addEventListener('change',()=>{const file=input.files?.[0];if(!file)return;audio.src=URL.createObjectURL(file);document.querySelector('#songTitle').textContent=file.name;audio.play().catch(()=>{});if(!audioCtx){audioCtx=new AudioContext();analyser=audioCtx.createAnalyser();analyser.fftSize=256;freq=new Uint8Array(analyser.frequencyBinCount);source=audioCtx.createMediaElementSource(audio);source.connect(analyser);analyser.connect(audioCtx.destination)}audioCtx.resume().catch(()=>{})});}
function audioState(){if(!analyser)return{intensity:.12,bass:.08,treble:.08};analyser.getByteFrequencyData(freq);let sum=0,bass=0,treble=0;for(let i=0;i<freq.length;i++){const v=freq[i]/255;sum+=v;if(i<freq.length*.18)bass+=v;if(i>freq.length*.58)treble+=v}return{intensity:clamp(sum/freq.length*1.9),bass:clamp(bass/(freq.length*.18)*1.5),treble:clamp(treble/(freq.length*.42)*1.5)}}
function input(dt){let x=(keys.has('d')||keys.has('arrowright'))-(keys.has('a')||keys.has('arrowleft'));let y=(keys.has('s')||keys.has('arrowdown'))-(keys.has('w')||keys.has('arrowup'));const l=Math.hypot(x,y)||1;x/=l;y/=l;const sprint=keys.has('shift')&&player.stamina>0;const speed=sprint?280:175;player.vx=x*speed;player.vy=y*speed;if(sprint&&(x||y))player.stamina=clamp(player.stamina-dt*.35);else player.stamina=clamp(player.stamina+dt*.22);player.x+=player.vx*dt;player.y+=player.vy*dt;if(keys.has(' ')&&player.dodge<=0&&player.stamina>.18){player.dodge=.28;player.invuln=.34;player.stamina-=.18;pushVFX('DODGE',player.x,player.y,.7,{maxLife:.3})}if(player.dodge>0){player.x+=x*260*dt;player.y+=y*260*dt;player.dodge-=dt}player.invuln=Math.max(0,player.invuln-dt);player.attack=Math.max(0,player.attack-dt)}
function attack(){if(player.attack>0||!window.echoVoidCore?.attack)return;player.attack=.32;pushVFX('PLAYER_ATTACK',player.x,player.y,.8,{maxLife:.22});window.echoVoidCore.attack(player.x,player.y,58,0.42)}
function spawnFromMusic(a){const core=window.echoVoidCore;if(!core||a.intensity<.18||spawnClock>0)return;const kind=a.bass>.62?1:a.treble>.62?2:(a.intensity>.68?3:4);const angle=Math.random()*Math.PI*2;const distance=420+Math.random()*360;const x=player.x+Math.cos(angle)*distance;const y=player.y+Math.sin(angle)*distance;const entry=kind===1?0:kind===2?1:kind===3?2:Math.floor(Math.random()*3);core.spawn(x,y,kind,entry,a.intensity);const fx=entry===0?'GROUND_EMERGE':entry===1?'SKY_DROP':'MUSIC_PORTAL';pushVFX(fx,x,y,a.intensity,{entry,kind,angle,maxLife:entry===1?.95:.8});spawnClock=Math.max(.16,.72-a.intensity*.48)}
function updateHud(a,frame){const pct=Math.round(a.intensity*100);document.querySelector('#intensityBar').style.width=pct+'%';document.querySelector('#echoBar').style.width=Math.round((a.bass+a.treble)*50)+'%';const threat=document.querySelector('#threat');const d=frame?.danger??a.intensity;threat.textContent=d>.78?'CRITICAL':d>.48?'DANGEROUS':d>.2?'UNEASY':'CALM'}
function tick(now){const dt=Math.min(.033,(now-last)/1000);last=now;spawnClock=Math.max(0,spawnClock-dt);mutationClock+=dt;updateVFX(dt);const a=audioState();input(dt);spawnFromMusic(a);if(window.echoVoidCore?.set_mutation&&mutationClock>.5){const level=a.intensity>.82?3:a.intensity>.62?2:a.intensity>.38?1:0;window.echoVoidCore.set_mutation(level);mutationClock=0}let frame=null;if(window.echoVoidCore?.tick){frame=window.echoVoidCore.tick(dt,player.x,player.y,a.intensity,player.calm<.08);if(frame?.playerDamage&&!player.invuln){player.health=clamp(player.health-frame.playerDamage);player.calm=clamp(player.calm-frame.playerDamage*.8);player.vx=frame.knockbackX;player.vy=frame.knockbackY;player.invuln=.28;pushVFX('PLAYER_HIT',player.x,player.y,.9,{maxLife:.35})}}player.calm=clamp(player.calm+dt*(.025-a.intensity*.035));if(player.health<=0){pushVFX('PLAYER_DEATH',player.x,player.y,1,{maxLife:1});player.health=1;player.calm=.45;player.x=0;player.y=0;window.echoVoidCore?.clear?.()}const renderer=window.echoVoidGpuRenderer;if(renderer?.ready)renderer.render({time:now/1000,player,monsters:presentMonsters(frame),safeZones:[],boss:null,accent:'#a9e8ff',accentRgb:[.66,.91,1],bg:[.035,.04,.07],intensity:a.intensity,bass:a.bass,treble:a.treble,playerVX:player.vx,playerVY:player.vy,sprinting:keys.has('shift'),dodging:player.dodge>0,vfx:vfxEvents});updateHud(a,frame);requestAnimationFrame(tick)}
window.EchoVoidVFX={events:vfxEvents,clear(){vfxEvents.length=0}};
window.EchoVoidGameplay={start(){for(const k of ['keydown','keyup'])window.addEventListener(k,e=>{const key=e.key.toLowerCase();if(k==='keydown'&&[' ','arrowup','arrowdown','arrowleft','arrowright','enter'].includes(key))e.preventDefault();if(k==='keydown'&&key==='enter')attack();k==='keydown'?keys.add(key):keys.delete(key)});window.addEventListener('pointerdown',attack);setupAudio();requestAnimationFrame(tick)}};
